Add package with ansible roles
artefactual-labs/am-packbuild pull request #247
Opened 2019-12-03 18:25 UTC by scollazo

2020-01-27 17:31 UTC, scollazo commented
This package is needed by nha, we don't have other way to get our roles into the environment.

2020-02-03 11:42 UTC, mamedin requested changes

2020-02-03 11:42 UTC, mamedin commented on rpm/archivematica-ansible-roles/package.spec
> +Source0: https://github.com/artefactual/archivematica-storage-service/
Hi Santi, do you need this line?

2021-01-29 11:09 UTC, scollazo commented on rpm/archivematica-ansible-roles/package.spec
> +Source0: https://github.com/artefactual/archivematica-storage-service/
Removed

2021-05-31 08:06 UTC, merged